routes/web.php
<?php

use App\Http\Controllers\MessagesController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
DB::listen(function($query){
    // echo "<pre>{$query->sql}</pre>";
});


Route::get('/', [PagesController::class, 'home' ]) -> name('home') ->middleware('example');

Route::get('saludos/{nombre?}', [PagesController::class, 'saludo' ]) -> name('saludos') ->where('nombre', "[A-Za-z]+");

Route::resource('mensajes', MessagesController::class);
Route::resource('usuarios', UsersController::class);

Auth::routes(['verify' => true]);



// Route::get('mensajes', [MessagesController::class, 'index' ]) -> name('messages.index');
// Route::get('mensajes/create', [MessagesController::class, 'create' ]) -> name('messages.create');
// Route::post('mensajes', [MessagesController::class, 'store' ]) -> name('messages.store');
// Route::get('mensajes/{id}', [MessagesController::class, 'show' ]) -> name('messages.show');
// Route::get('mensajes/{id}/edit', [MessagesController::class, 'edit' ]) -> name('messages.edit');
// Route::put('mensajes/{id}', [MessagesController::class, 'update' ]) -> name('messages.update');
// Route::delete('mensajes/{id}', [MessagesController::class, 'destroy' ]) -> name('messages.destroy');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use App\Models\Message;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
        'role'
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function hasRoles($role)
    {
        $this->role === $role;
    }

    public function messages()
    {
        return $this->hasMany(Message::class);
    }

    public function note()
    {
        return $this->morphOne(Note::class, 'notable');
    }

    public function tags()
    {
        return $this->morphToMany(Tag::class, 'taggable')->withTimestamps( );
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UpdateUserRequest;
use App\Models\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{

    function __construct()
    {
        $this->middleware('auth');
        $this->middleware('roles:admin', ['except' => ['edit', 'update', 'show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);

        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        // $this->authorize($user);

        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, $id)
    {
        $user = User::findOrFail($id);


        $this->authorize($user);
        $user->update($request->all());

        return back()->with('info', 'Usuario actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);

        $this->authorize($user);
        $user->delete();

        return back();
    }
}

resources/views/users/edit.blade.php
@extends('layout')
@extends('layouts.app')


@section('contenido')

    <h1>Editar Usuario</h1>
    @if (session()->has('info'))
    <div class="alert alert-success">{{ session('info') }}</div>
    @endif
    <form class="row justify-content-center" method="post" action="{{ route('usuarios.update', $user->id) }}">
        {{-- <input type="hidden" name="_token" value="{{ csrf_token() }}"> --}}
        {!! csrf_field() !!}
        {!! method_field('put') !!}
        <label class="col-md-8" for="nombre">
            Nombre
            <input class="row mb-3 form-control" type="text" name="nombre" value="{{$user->nombre}}">
            {!! $errors->first('nombre', '<span class="error">:message</span>') !!}
        </label>
        <label class="col-md-8" for="email">
            Email
            <input class="row mb-3 form-control" type="text" name="email" value="{{$user->email}}">
            {!! $errors->first('email', '<span class="error">:message</span>') !!}

        </label>
        <input class="btn btn-primary col-md-5 " type="submit" value="Enviar">
    </form>
@stop

resources/views/users/index.blade.php
@extends('layout')
@extends('layouts.app')


@section('contenido')

    <h1>Usuarios</h1>
    <table class="table ">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Email</th>
                <th>Role</th>
                <th>Notas</th>
                <th>Etiquetas</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
            <tr>
                <td>{{ $user->id }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->role }}</td>
                <td>{{$user->note ? $user->note->body : ''  }}</td>
                <td>{{$user->tags ?  $user->tags->pluck('name')->implode(', ') : ''  }}</td>
                


            <td class="d-inline-flex p-2">
                <a class="btn btn-info btn-xs" href="{{ route('usuarios.edit', $user->id) }}"> Editar</a>
                <form method="POST" action="{{ route('usuarios.destroy', $user->id) }}">
                    {!! csrf_field() !!}
                    {!! method_field('delete') !!}
                    <button class="btn btn-danger btn-xs" type="submit">Eliminar</button>
                </form>
            </td>
</tr>
 @endforeach
        </tbody>
    </table>
@stop

resources/views/users/show.blade.php
@extends('layout')
@extends('layouts.app')


@section('contenido')

    <h1>{{ $user->name }}</h1>
    <table class="table">
        <tr>
            <th>Nombre:</th>
            <td>{{ $user->name }}</td>
        </tr>
        <tr>
            <th>Email:</th>
            <td>{{ $user->email }}</td>
        </tr>
        <tr>
            <th>Rol:</th>
            <td>{{ $user->role }}</td>
        </tr>
    </table>
<div class="d-inline-flex p-2">
    @can('edit', $user)
        <a href="{{ route('usuarios.edit', $user->id)}}"class="btn btn-info">Editar</a>
    @endcan
    @can('destroy', $user)
    <form method="POST" action="{{ route('usuarios.destroy', $user->id) }}">
        {!! csrf_field() !!}
        {!! method_field('delete') !!}
        <button class="btn btn-danger btn-xs" type="submit">Eliminar</button>
    </form>
    @endcan
</div>
@stop