routes/web.php
<?php

use App\Http\Controllers\MessagesController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
DB::listen(function($query){
    // echo "<pre>{$query->sql}</pre>";
});


Route::get('/', [PagesController::class, 'home' ]) -> name('home') ->middleware('example');

Route::get('saludos/{nombre?}', [PagesController::class, 'saludo' ]) -> name('saludos') ->where('nombre', "[A-Za-z]+");

Route::resource('mensajes', MessagesController::class);
Route::resource('usuarios', UsersController::class);

Auth::routes(['verify' => true]);



// Route::get('mensajes', [MessagesController::class, 'index' ]) -> name('messages.index');
// Route::get('mensajes/create', [MessagesController::class, 'create' ]) -> name('messages.create');
// Route::post('mensajes', [MessagesController::class, 'store' ]) -> name('messages.store');
// Route::get('mensajes/{id}', [MessagesController::class, 'show' ]) -> name('messages.show');
// Route::get('mensajes/{id}/edit', [MessagesController::class, 'edit' ]) -> name('messages.edit');
// Route::put('mensajes/{id}', [MessagesController::class, 'update' ]) -> name('messages.update');
// Route::delete('mensajes/{id}', [MessagesController::class, 'destroy' ]) -> name('messages.destroy');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Message.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    use HasFactory;
    protected $fillable = ['nombre', 'email', 'mensaje'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function note()
    {
        return $this->morphOne(Note::class, 'notable');
    }

    public function tags()
    {
        return $this->morphToMany(Tag::class, 'taggable');
    }
}

app/Http/Controllers/MessagesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Message;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;

class MessagesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $messages = DB::table('messages')->get();
        $messages = Message::with(['user', 'note', 'tags'])
            ->orderBy('created_at', request('sorted', 'DESC'))
            ->simplePaginate(10);

        

        return view('messages.index', compact('messages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('messages.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // Guardar mensaje
        //    DB::table('messages')->insert([
        //        "nombre" => $request->input('nombre'),
        //        "email" => $request->input('email'),
        //        "mensaje" => $request->input('mensaje'),
        //        "created_at" => Carbon::now(),
        //        "updated_at" => Carbon::now(),
        //    ]);

        // Model::unguard();

        $message = Message::create($request->all());

        // if (auth()->check()) {
        //     auth()->user()->messages()->save($message);
        // }

        $message->user_id = auth()->id();
        $message->save();

        Mail::send('emails.contact', ['msg' => $message], function($m) use ($message){
            $m->to($message->email, $message->name)->subject('Tu mensaje fue recibido');
        });

        //    Redireccionar
        return redirect()->route('mensajes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $message = DB::table('messages')->where('id', $id)->first();
        $message = Message::findOrFail($id);

        return view('messages.show', compact('message'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // $message = DB::table('messages')->where('id', $id)->first();
        $message = Message::findOrFail($id);

        return view('messages.edit', compact('message'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // DB::table('messages')->where('id', $id)->update([
        //     "nombre" => $request->input('nombre'),
        //     "email" => $request->input('email'),
        //     "mensaje" => $request->input('mensaje'),
        //     "updated_at" => Carbon::now(),
        // ]);

        $message = Message::findOrFail($id);
        $message->update($request->all());

        return redirect()->route('mensajes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Eliminar mensaje
        // DB::table('messages')->where('id', $id)->delete();
        $message = Message::findOrFail($id)->delete();

        // Redireccionar
        return redirect()->route('mensajes.index');
    }
}

resources/views/messages/create.blade.php
@extends('layout')
@extends('layouts.app')


@section('contenido')

<h1 class="text-center">Contactos</h1>
<h2 class="text-center">Escríbeme</h2>
@if (session()->has('info'))
    <h3>{{ session('info') }}</h3>
@else
<form class="row justify-content-center" method="post" action="{{ route('mensajes.store') }}">
   @include('messages.form', ['message'])
</form>
@endif
@stop

resources/views/messages/edit.blade.php
@extends('layout')
@extends('layouts.app')

@section('contenido')

    <h1 class="text-center mb-5">Editar mensaje de {{ $message->nombre }} </h1>

    <form class="row justify-content-center" method="post" action="{{ route('mensajes.update', $message->id) }}">
        {{-- <input type="hidden" name="_token" value="{{ csrf_token() }}"> --}}
        {!! csrf_field() !!}
        {!! method_field('put') !!}
       @include('messages.form', ['btnText' => 'Actualizar'])
    </form>
@stop

resources/views/messages/form.blade.php
 {{-- <input type="hidden" name="_token" value="{{ csrf_token() }}"> --}}
 {!! csrf_field() !!}
 @unless (isset($message) and $message->user_id)
 <label class="col-md-8" for="nombre">
     Nombre
     <input class="row mb-3 form-control" type="text" name="nombre" value="{{$message->nombre ?? old('nombre')}}">
     {!! $errors->first('nombre', '<span class="error">:message</span>') !!}
 </label>
 <label class="col-md-8" for="email">
     Email
     <input class="row mb-3 form-control" type="text" name="email" value="{{$message->email ?? old('email')}}">
     {!! $errors->first('email', '<span class="error">:message</span>') !!}

 </label>
 @endunless

 <label class="col-md-8" for="mensaje">
     Mensaje
     <textarea class="row mb-3 form-control" name="mensaje">{{$message->mensaje ?? old('mensaje')}}</textarea>
     {!! $errors->first('mensaje', '<span class="error">:message</span>') !!}
 </label>
 <input class="btn btn-primary col-md-5 " type="submit" value="{{  $btnText ?? 'Guardar' }}">

resources/views/messages/index.blade.php
@extends('layout')
@extends('layouts.app')

@section('contenido')

    <div class="">
        <h1 class="text-center">Todos los mensajes</h1>
        <table class="table container h-100 ">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Email</th>
                    <th>Mensaje</th>
                    <th>Notas</th>
                    <th>Etiquetas</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach($messages as $message)
                <tr>
                    @if ($message->user_id)
                    <td>{{ $message->user->name }}</td>
                    <td>{{ $message->user->email }}</td>
                    @else
                    <td>{{ $message->nombre }}</td>
                    <td>{{ $message->email }}</td>
                    @endif
                    <td>
                        <a href="{{ route('mensajes.show', $message->id) }}">{{ $message->mensaje }}</a>
                    </td>
                    <td>{{$message->note ? $message->note->body : ''  }}</td>
                    <td>{{$message->tags ? $message->tags->pluck('name')->implode(', ') : ''  }}</td>
                    <td class="d-inline-flex p-2">
                        <a class="btn btn-info btn-xs" href="{{ route('mensajes.edit', $message->id) }}"> Editar</a>
                        <form method="POST" action="{{ route('mensajes.destroy', $message->id) }}">
                            {!! csrf_field() !!}
                            {!! method_field('delete') !!}
                            <button class="btn btn-danger btn-xs" type="submit">Eliminar</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
            {{ $messages->fragment('hash')->appends(request()->query())->links('pagination::simple-bootstrap-5') }}
        </table>
    </div>
@stop

resources/views/messages/show.blade.php
@extends('layout')
@extends('layouts.app')

@section('contenido')

    <h1>Mensaje</h1>
    <p>Enviado por {{ $message->nombre }} -{{ $message->email }}</p>
    <p> {{ $message->mensaje }} </p>

@stop