routes/web.php
<?php

use App\Http\Controllers\MessagesController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
DB::listen(function($query){
    // echo "<pre>{$query->sql}</pre>";
});


Route::get('/', [PagesController::class, 'home' ]) -> name('home') ->middleware('example');

Route::get('saludos/{nombre?}', [PagesController::class, 'saludo' ]) -> name('saludos') ->where('nombre', "[A-Za-z]+");

Route::resource('mensajes', MessagesController::class);
Route::resource('usuarios', UsersController::class);

Auth::routes(['verify' => true]);



// Route::get('mensajes', [MessagesController::class, 'index' ]) -> name('messages.index');
// Route::get('mensajes/create', [MessagesController::class, 'create' ]) -> name('messages.create');
// Route::post('mensajes', [MessagesController::class, 'store' ]) -> name('messages.store');
// Route::get('mensajes/{id}', [MessagesController::class, 'show' ]) -> name('messages.show');
// Route::get('mensajes/{id}/edit', [MessagesController::class, 'edit' ]) -> name('messages.edit');
// Route::put('mensajes/{id}', [MessagesController::class, 'update' ]) -> name('messages.update');
// Route::delete('mensajes/{id}', [MessagesController::class, 'destroy' ]) -> name('messages.destroy');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                        <li class="nav-item"><a class="nav-link" href=" {{ route('saludos', 'Invitado') }}">Saludos</a></li>
                        <li class="nav-item"><a class="nav-link" href=" {{ route('mensajes.create')}} ">Contactos</a></li>
                        @if (auth()->check())
                            <li class="nav-item"><a class="nav-link" href=" {{ route('mensajes.index')}} ">Mensajes</a></li>
                            @if (auth()->user()->role === 'admin')
                            <li class="nav-item"><a class="nav-link" href=" {{ route('usuarios.index') }}">Usuarios</a></li>
                            @endif
                            @endif
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                                  

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>